Assertion failures result in raising an AssertionError